# Action exécutée sur les pull_request et les push branches main et releases
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

# Travaux
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

    - name: Extraire le dépôt
      uses: actions/checkout@master

    - name: Upload dans FRW
      uses: MTESSDev/github-action-mtess-frw-deploiement@main
      with:
        url: 'https://formulaires.it.mtess.gouv.qc.ca/api/v1/SIS/DeployerSysteme'
        repertoire: '${{ github.workspace }}'
        customHeaders: '{"Content-Type": "application/json", "X-ApiKey": "${{ secrets.APIKEY }}", "X-NoPublicSystemeAutorise": "${{ secrets.NOPUBLICSYSTEMEAUTORISE }}"}'
        data: '{"zip": "${{ steps.base64Zip.outputs.base64 }}"}'
