on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://formulaires.it.mtess.gouv.qc.ca/api/v1/SIS/DeployerSysteme'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json", "X-ApiKey": "JFEsvQ6ALUzLbhsVaJUM9MtMbLnLUpcfYd7NS5GLYXDuRWpFZNw5rKt45J3L", "X-NoPublicSystemeAutorise": "B4CF56AE-8F79-413C-939C-71F1DA4BC807"}'
        data: '{"zip": ""}'
